config/routes.rb
Rails.application.routes.draw do

  resources :lists do
    resources :tasks
  end

  root 'lists#index'
end

app/models/list.rb
class List < ActiveRecord::Base
  has_many :tasks

  before_destroy :destroy_tasks

  validates :name, :presence => true

  private

  def destroy_tasks
    self.tasks.destroy_all
  end
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :list

  validates :description, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]


  def index
    @lists = List.all
  end


  def show
  end

  def new
    @list = List.new
  end

  def edit
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to  lists_path
    else
      render :new
    end
  end

  def update
    if @list.update(list_params)
      redirect_to lists_path
    else
      render :edit
    end
  end

  def destroy
    @list.destroy
    redirect_to lists_path
  end

  private
    def set_list
      @list = List.find(params[:id])
    end

    def list_params
      params.require(:list).permit(:name)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :set_list, only: [:new, :create, :index, :edit, :update, :destroy]


  def index
    @tasks = @list.tasks
  end


  def show
  end

  def new
    @task = @list.tasks.new
  end

  def edit
  end

  def create
    @task = @list.tasks.new(task_params)

    if @task.save
      redirect_to  list_path(@list)
    else
      render :new
    end
  end

  def update
    if @list.tasks.update(@task, task_params)
      redirect_to  list_path(@list)
    else
      render :edit
    end
  end


  def destroy
    if @task.destroy
      redirect_to list_path(@list)
    else
      render edit
    end
  end

  private
    def set_task
      @task = Task.find(params[:id])
    end

    def set_list
      @list = List.find(params[:list_id])
    end

    def task_params
      params.require(:task).permit(:description, :list_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Www</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/lists/_form.html.erb
<% if @list.errors.any? %>
  <h3>Oops there were some errors. Please try again:</h3>
  <ul>
    <% @list.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for(@list) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/lists/edit.html.erb
<h1>Editing List</h1>

<%= render 'form' %>

<%= link_to 'Show', @list %> |
<%= link_to 'Back', lists_path %>

app/views/lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Lists</h1>

<ul>
  <% @lists.each do |list| %>
    <li><%= link_to list.name, list %></li>
  <% end %>
</ul>

<%= link_to 'New List', new_list_path %>

app/views/lists/new.html.erb
<h1>New List</h1>

<%= render 'form' %>

<%= link_to 'Back', lists_path %>

app/views/lists/show.html.erb
<p id="notice"><%= notice %></p>

<%= @list.name %>

<%= link_to 'Edit', edit_list_path(@list) %> |
<%= link_to 'Delete', list_path(@list), :data => {:confirm => "Lets do this?", :method => "delete"} %> |


<% if @list.tasks.any? %>
<ul>
  <% @list.tasks.each do |task| %>
    <li>
      <%= link_to task.description, edit_list_task_path(@list, task) %>
<%= link_to 'Delete', list_task_path(@list, task), :data => {:confirm => "Lets do this?", :method => "destroy"} %> |
    </li>
  <% end %>
<% else %>
  <p>Lets add some tasks!</p>
</ul>
<% end %>

<%= link_to 'Add New Task', new_list_task_path(@list) %> |

<%= link_to 'Back', lists_path %>

app/views/tasks/_form.html.erb
<%= form_for [@list, @task]  do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :list_id %><br>
    <%= f.number_field :list_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form' %>

<%= link_to 'Back', list_path(@list) %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form' %>

<%= link_to 'Back', list_path(@list) %>